# Generated by Django 3.0.5 on 2020-04-20 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('price', models.IntegerField()),
                ('months', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_by', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.ForeignKey(default='free', on_delete=django.db.models.deletion.CASCADE, to='member.MembershipType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='logo.png', upload_to='member/profile_pictures/')),
                ('cnic', models.TextField(blank=True, max_length=13)),
                ('birth_date', models.DateField(blank=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('phone_number', models.TextField(blank=True, max_length=11)),
                ('address', models.TextField(blank=True, max_length=256)),
                ('city', models.TextField(blank=True, max_length=256)),
                ('state', models.TextField(blank=True, max_length=256)),
                ('country', models.TextField(blank=True, max_length=256)),
                ('cnic_pic_front', models.ImageField(blank=True, upload_to='member/cnic/')),
                ('cnic_pic_rear', models.ImageField(blank=True, upload_to='member/cnic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
