# Generated by Django 3.0.5 on 2020-04-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200423_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
