# Generated by Django 3.0.5 on 2020-04-23 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0004_auto_20200423_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='id',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='id',
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='max_levels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='max_referrals',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='referral',
            name='total_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='User', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
