# Generated by Django 3.0.5 on 2020-04-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20200423_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='commission_percentage',
            field=models.IntegerField(default=5),
        ),
    ]
