# Generated by Django 3.0.5 on 2020-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20200426_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='commission',
            field=models.FloatField(default=0),
        ),
    ]
