# Generated by Django 3.0.5 on 2020-04-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20200429_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='account',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='member',
            name='referral',
        ),
    ]
