# Generated by Django 3.0.5 on 2020-04-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20200429_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Account'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Membership'),
        ),
        migrations.AlterField(
            model_name='member',
            name='referral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Referral'),
        ),
    ]
