# Generated by Django 3.0.5 on 2020-05-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='anonymous', max_length=150),
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(default='12345678910', max_length=11),
        ),
    ]
