# Generated by Django 3.0.5 on 2020-05-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_auto_20200520_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='cnic',
            field=models.CharField(max_length=13),
        ),
    ]
