# Generated by Django 3.0.5 on 2020-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_auto_20200520_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
