# Generated by Django 3.0.5 on 2020-05-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_auto_20200520_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cnic',
            field=models.CharField(help_text='Without dashes', max_length=13),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(help_text='Starting with 03XX', max_length=11),
        ),
    ]
