# Generated by Django 3.0.5 on 2020-05-23 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0022_auto_20200523_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('conditions', models.TextField(max_length=10240)),
                ('bonus', models.FloatField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.MembershipType')),
            ],
        ),
        migrations.CreateModel(
            name='RewardClaimRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Rewards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
